FROM bcit.io/php-fpm:<%= image.vars['php_version'] %>-centos-latest

RUN yum install -y less \
  && rm -rf /var/cache/yum

ADD https://github.com/wp-cli/wp-cli/releases/download/v<%= image.vars['wpcli_version'] %>/wp-cli-<%= image.vars['wpcli_version'] %>.phar \
    /usr/local/bin/wp
RUN chmod 555 /usr/local/bin/wp \
 && adduser -D -h /application wordpress


CMD ["init-loop"]
